### ISSUE TITLE
Zen mode causes Obsidian to become unresponsive

### ISSUE THREAD

**Issue by kahboom** [oxdc/obsidian-vertical-tabs#12]
Thank you for developing this wonderful (and incredibly useful!) plugin. As the title suggests, clicking on zen mode is causing Obsidian to become unresponsive for me (macOS Sonoma 14.5). I also wanted to ask if zen mode supports canvas view? I did test with and without a canvas and am getting the same issue. Please let me know if you need additional information.

**Comment by oxdc** [comment]
Thanks for your feedback!

> if zen mode supports canvas view?

Of course! And it works fine on my Mac (macOS Sonoma 14.6.1).

> Please let me know if you need additional information.

Could you please provide me the debug information? You may follow these steps:

1. Open "Command Palette";
2. Type "Show debug info" and hit enter;
3. Click "Copy to clipboard";
4. Paste here.

**Some suggestions for debugging:**
Could you please install *Vertical Tabs* in the Sandbox vault, which can be opened by clicking the help button. Always use the default theme and disable all the snippets and other plugins before testing. Since:

1. Another plugin might be incompatible with *Vertical Tabs*;
2. Some CSS settings might cause performance issues, making Obsidian become unresponsive.

Additional note: apparently, the same issue has been discovered recently by users without *Vertical Tabs* installed and is caused by a few community themes.

**Comment by Azona77** [comment]
I encountered once, but could not reproduce after relaunch or in sandbox.

**Comment by oxdc** [comment]
Hope it won't happen again. But if it does, could you please check the CPU and memory usage of Obsidian in the [Active Monitor](https://support.apple.com/guide/activity-monitor/welcome/mac). Some memory leaks could cause this issue.

**Comment by oxdc** [comment]
This issue is closed as no updates are received. Please reopen this if you have experienced similar issues again. Thank you.
