### ISSUE TITLE
Support multiple windows

### ISSUE THREAD

**Issue by Trebuchosaure** [oxdc/obsidian-vertical-tabs#22]
Hello,
thank you very much for your plugin, it's very useful ! 
I work with multiple windows, but the plugin only recognize the tabs and groups open in the main one, it is possible to get those open in other windows ? thanks for your answer.

**Comment by oxdc** [comment]
Hi! Thank you for suggesting. I'm not sure if this is possible or the best option. I'll check with this.

By the way, could please explain why would you use multiple windows with multiple tabs open? Since most people don't have many open tabs in secondary windows and the design of Obsidian encourages the following use pattern:

- You are encouraged to work primarily on a single window to focus on your work.
- The main window provides sidebars, in which auxiliary information is gathered.
- _Vertical Tabs_ should be in the sidebar. There must be exactly only one instance of _Vertical Tabs_.
- You may open, duplicate or move a few active notes to a secondary window only for some special purposes, for example, pinning on the top of the window stack, moving to another monitor.
- If you want to put the notes side by side, you should use workspace split instead.

Excluding tabs in secondary windows is not a missing feature of _Vertical Tabs_, instead, it is designed to be so. But I will consider your suggestion if it is technically possible.

**Comment by oxdc** [comment]
Good news! It is technically possible: bc370c050b520d81745caa4c840875ecbcf5ed15. Still working on it.

**Comment by Trebuchosaure** [comment]
Hi,
thank you for your quick answer !  And I'm glad it's possible ! 
Yes, I'm working on dual monitor, I use the secondary one to show text references, or stuff like that. But sometimes I need to have multiple tabs on my secondary monitor.

thanks again !

**Comment by oxdc** [comment]
Tabs in secondary windows are now visible in *Vertical Tabs*. There are still some limitations, though,

- *Vertical Tabs* should be in the sidebar. There must be exactly only one instance of *Vertical Tabs*.
- Features like *Zen Mode* and *Show Active Tabs* only work in the main window.

Further refinement requires a huge refactoring, but will come in the future. Stay tuned!

If you have other suggestions or run into some issues, feel free to reopen this issue if related, or open another issue. Thanks!
