### ISSUE TITLE
Tab groups for sidebars

### ISSUE THREAD

**Issue by N3C2L** [oxdc/obsidian-vertical-tabs#3]
I often drag and drop tabs into the left or right sidebar.
Could it be implemented that these tabs will be displayed also as tab groups in the vertical tabs sidebar?
Would be awesome!

**Comment by oxdc** [comment]
Could you please elaborate on this use case? To get the UX right, I would like to understand how do you use the sidebars. 

Given the UI design of Obsidian, the left sidebar is primarily for navigation, such as file explorer, tag panel, global search, etc., while the right sidebar is a stage for plugins and extensions, a kind of supplementary view, for example, calendar, backlinks, etc.

May I ask what kind of tabs would you like to put in the sidebars? Are there some notes? If so, what kind of situation would make this note-in-the-sidebar layout useful?

For me, if I want a side-to-side view, I would drag a note to make a new split. When the screen space is small, I maybe temporarily hide the sidebars. The way the Obsidian team designed simply encourages usage like this, since it might not be a good idea to open too many sidebar tabs. Besides, I need to handle the sidebar tabs carefully. Simply put, we need to put the Vertical Tab view itself into the sidebar, thus managing sidebars means managing its own view as well. Sometimes, this can be tricky and subtle.

**Comment by N3C2L** [comment]
Yes, thank you for your feedback. It’s true that it may be unusual for some and could certainly just be an optional setting for people who find the screen too small. For this purpose, I have adjusted my sidebars with CSS so that when my mouse touches the edge of the screen, they are shown or hidden:

/* hide right sidebar */
.workspace-split.mod-horizontal.mod-right-split {
    width: 1px !important;
    transition: 0s;
    transition-delay: 50ms;
}

/* reveal right sidebar on hover */
.workspace-split.mod-horizontal.mod-right-split:hover {
    width: 450px !important;
    transition: 0s;
}

I use this sidebar tabs for example quick notes or Dataview views. To have them visible in your plugin is not a high priority, but it would be a nice addition to your plugin. Perhaps a long-term consideration when you have the time.

**Comment by oxdc** [comment]
Thanks! I'm wondering if it is okay to only show markdown tabs in the sidebars?

**Comment by N3C2L** [comment]
That would be totally fine!

**Comment by oxdc** [comment]
This feature would be avaliable in the next major release. More options are under active dev. 🎉

<img width="357" alt="SCR-20240731-bihx" src="https://github.com/user-attachments/assets/fbf8fce9-62ba-4365-a9ec-3f153395d4f1">

**Comment by N3C2L** [comment]
This looks truly amazing! 
Happy and looking forward to the next major release! 🎉

**Comment by N3C2L** [comment]
Excellent! Everything works well, just as you showed in your new video in the readme. The new side panel tab groups and the drag and drop feature are great improvements that make working with tabs easier. Thank you!
