### ISSUE TITLE
Drag and drop within the vertical tabs view

### ISSUE THREAD

**Issue by nickchomey** [oxdc/obsidian-vertical-tabs#4]
The only way to move tabs between groups seems to be to toggle "Show all tabs" and then drag from one pane to another. 

It would be great if we could drag and drop tabs between different tab groups from within the vertical tabs view. 

And if we drag beyond the groups, it should create a new group

**Comment by oxdc** [comment]
Hi, @nickchomey . This feature requires some hacking into private APIs of Obsidian, since no explicit interface is exposed. I'm trying to get this work right now.

**Comment by oxdc** [comment]
> It would be great if we could drag and drop tabs between different tab groups from within the vertical tabs view.

Check out the latest version (v0.2.0) and the demo video. 🎉🎉


https://github.com/user-attachments/assets/2fbd761a-065a-4415-a4a1-1ba204fb5ead

> And if we drag beyond the groups, it should create a new group

Group creation is not available yet, but you may always drag the open tab (the native tab managed by Obsidian) to create a new group. Since this is another issue to be addressed, I will close this issue for now.

---

If you find bugs or missing features, you may open a new issue.

P.S. Vertical Tabs is now available in Community Plugin store, you may update directly from there.
