### ISSUE TITLE
Reloading bookmarked files/folders

### ISSUE THREAD

**Issue by Lotus49b** [oxdc/obsidian-vertical-tabs#42]
Nice feature, thanks!

I see that when I re-open a saved folder containing a file from Bookmarks, Vertical Tabs creates a new folder called "Grouped tabs" and doesn't return the folder name as it was initially bookmarked.

Step 1: Save this folder to Bookmarks
![image](https://github.com/user-attachments/assets/93331085-3cde-49a7-b5e4-061a8f3556d4)

Step 2: Re-open folder from bookmarks
![image](https://github.com/user-attachments/assets/b22b76c1-fdc6-474c-b831-73749201ea48)

Step 3: The file is back in Vertical Tabs but the original folder name is lost
![image](https://github.com/user-attachments/assets/0f890a1b-b21c-496f-9bc8-ff7d25a1b6e4)

**Comment by oxdc** [comment]
Thank you. This is the intended behavior (at least for now). There would be two ways for users to store tab groups:

1. (implemented & shipped) bookmark the group;
2. (working on) stash the group into the "later" box.

For Method 1: Bookmarking works with the core plugin and should be used as it is. When you bookmark a group, the name is sent from *Vertical Tabs* to *Bookmark*. However, when you open a group of bookmarks, a **new** group is created by *Bookmark*, **NOT** by *Vertical Tabs*. Because *Vertical Tabs* cannot distinguish manually created bookmark groups from saved tab groups, it should not make assumptions and modify the name.

Method 2 has more features. When a tab group is stashed, the cursor positions and history records are also remembered, which cannot be achieved with bookmarks.

**Comment by Lotus49b** [comment]
Thanks, method 2 sounds promising. I assume the "later" box will be inside VT? That will be nice and fast. The Bookmarks feature has never really clicked with me (joke not intended).

**Comment by oxdc** [comment]
> I assume the "later" box will be inside VT?

Yes! This will be a feature of *Vertical Tabs*.

**Comment by Azmoinal** [comment]
> Method 2 has more features. When a tab group is stashed, the cursor positions and history records are also remembered, which cannot be achieved with bookmarks.


It sounds very interesting.  I cannot wait to test it

**Comment by oxdc** [comment]
Since there would be some time before Method 2 coming out, after hacking into the build-in Bookmark plugin, I implemented Method 1 with automatic name reloading. When you open a bookmark group **created by _Vertical Tabs_**, the name of that group will be automatically set. Note that this only works when the bookmark is saved from _Vertical Tabs_ rather than manually created.
