### ISSUE TITLE
Order of Groups

### ISSUE THREAD

**Issue by shef-ski** [oxdc/obsidian-vertical-tabs#44]
Hello, just started using this (fantastic) plugin today and am not sure if this behaviour is intentional: the order of tab groups reverts each time I reopen my vault. Example of what it looks like initially:

<img width="192" alt="{52D3A34E-BA4E-4DBA-9340-4CF4DC016F0B}" src="https://github.com/user-attachments/assets/de342ef4-2f9f-4b70-ba9b-b3be8a8f3950">

and this is what it looks like after reopening (and collapsing all groups):

<img width="187" alt="{B03AA91C-8D9A-4984-B5F2-29061C2F958B}" src="https://github.com/user-attachments/assets/254a1634-f110-47bf-90bf-9b6dae74f8c5">

I noticed that the group order is the same every time I reopen but I wasn't able to determine the sorting logic (it's not alphabetical nor based on the number of pinned notes or anything like that at least). Is there a logic behind this sorting or is it more on the metadata level somewhere?

Best,
shefski

**Comment by oxdc** [comment]
Thank you for reporting the issue.

> Is there a logic behind this sorting?

Whenever *Vertical Tabs* reloads, it sorts the groups based on their hierarchy. Under the hood, each group is a workspace split of Obsidian. When you enabled the Zen Mode, the structure is hidden from you since only one split is visible on screen. You may see the full layout by temporarily disabling the Zen Mode. The order of these splits (or groups) is managed natively by Obsidian and *Vertical Tabs* only displays it.

When you manually reorder the groups, the original split hierarchy will _not_ be modified by design. This is because order synchronization for splits has no uniform behavior and will incur huge performance overhead. Besides, it will also break some users' workflow.

As the native hierarchy and order may have little value for most users, I'll make some changes to ensure the persistence of group orders ASAP.

**Comment by shef-ski** [comment]
Thanks a lot for the quick response! I was not familiar with workspace splits as I only ever look at one tab at the same time.

**Comment by oxdc** [comment]
This issue has been fixed in the latest version. Please update to v0.9.0. Thank you.
