### ISSUE TITLE
Unexpected behavior - new note appears in inactive folder group

### ISSUE THREAD

**Issue by Lotus49b** [oxdc/obsidian-vertical-tabs#49]
I've noticed this at various times. 

I open a new daily note (Friday) while I'm in the current folder/group (1). The daily note for Thursday is still open at this time (as seen in the top tab bar and in Vertical Tabs). 
The new daily note (Friday, created by Templater) then opens as expected, but instead of appearing in folder 1 (the active folder), it goes into folder 2 (inactive) instead.

Now I drag the new note to the correct folder (1)

![image](https://github.com/user-attachments/assets/6fd69c5a-b167-474e-87a4-e0cb31db4aa3)

**Comment by oxdc** [comment]
Thank you for providing the details. This, however, might be an issue with Obsidian because *Vertical Tabs* does not manage the creation of new tabs, the preferred location is automatically chosen by Obsidian.

The exact behavior is as follows:

- When your active tab is *not* pinned, the new note will appear in your current tab.
- When your active tab is pinned, the new note will appear in your latest unpinned tab. **If this unpinned tab is in another group, it will cause your problem.**
- When you open the new note **while holding the command (control) key**, a new tab will be created right after your active tab in the same group, which is what you expected.

While modifying the tab creation could cause more issues, *Vertical Tabs* will keep the current implementation. I'll close this issue right now. If you encounter related problems or need help, feel free to comment below.

**Comment by oxdc** [comment]
Hi @Lotus49b, I think I have figured a way out! See the demo video below.

At first, I'm working on note 2 in group A. Both notes in group A are pinned. The only available unpinned tab is note 3 in group B. So when I try to open note 4, note 3 get replaced and note 4 appears in group B, despite that group A is active. — This is Obsidian's original design, which causes your problem.

Then, I enabled a new feature called "Always open in new tab". After refocusing on note 2 in group A, this time, when I try to open note 4, it appears right after note 2 in the same group! — This is what you and many users expected.

https://github.com/user-attachments/assets/a706487a-9003-42ba-8855-dcd2af5cabf0

**Comment by Lotus49b** [comment]
That looks great! Look forward to this feature, thanks

**Comment by oxdc** [comment]
"Always open in new tab" should no longer break the Word Counter core plugin. This feature will be publicly available after some tests.

https://github.com/user-attachments/assets/e06e90e4-f927-4659-b085-866fc0a49982

**Comment by oxdc** [comment]
Hi @Lotus49b ! This issue should be resolved with the build-in smart navigation algorithm in the latest version. Other features regarding tab navigation are also publicly available. Please see [the announcement](https://github.com/oxdc/obsidian-vertical-tabs/releases/tag/0.12.1) for details.
