### ISSUE TITLE
Tab zoom is breaking Minimal theme css classes

### ISSUE THREAD

**Issue by Lotus49b** [oxdc/obsidian-vertical-tabs#63]
I don't know if this is limited to Minimal theme only.

With new VT tab zoom version, cssclasses are over-ridden/ignored:
![image](https://github.com/user-attachments/assets/d754be3b-a8fa-446f-93e4-c3b6a596de9b)

With VT disabled (or with VT 0.10 reinstalled):
![image](https://github.com/user-attachments/assets/8e8ebdbb-7568-4990-9308-b2ba075eb76f)

"Table-wide" allows the table width to extend beyond the normal Readable Line Length setting (table-small sets a smaller font in the table). 
I've reverted to v0.10 for now.

**Comment by oxdc** [comment]
Thank you! I'll look into it ASAP.

**Comment by oxdc** [comment]
Hi @Lotus49b ! After some inspections, it seems that Minimal theme does not follow Obsidian's default design and style structures. Since there is no CSS class or anchor for identifying the theme, I cannot apply patches to this specific theme. Or otherwise it will break other themes. Please consider opening a Plugin Support issue on their side. Thank you.

In the next release, tab zoom will only be applied if necessary. So, if you don't enable tab zoom, everything will work as usual.

**Comment by Lotus49b** [comment]
Great, thanks!
