### ISSUE TITLE
[Android] Mobile compatibility: unable to scroll without opening notes

### ISSUE THREAD

**Issue by shef-ski** [oxdc/obsidian-vertical-tabs#64]
On my mobile version, whenever I try to scroll through my vertical tabs by touching and swiping on a note tab, the tab opens immediately and interrupts the scrolling process. This happens regardless of how briefly I touch the tab, making navigation difficult. A current workaround is to scroll using the very edge of the vertical tabs area, but this region is quite narrow. 

I am using a Samsung Galaxy S21. 

If you cannot reproduce it and/or do not have the time, I could attempt to fix the issue myself and create a PR. I believe the issue resides with this part of the code within the Tabs.tsx, but I'm not certain:

const { listeners } = useTouchSensor({
minDistance: 10,
callback: (moved) => {
	if (!moved) openTab();
},
});

**Comment by shef-ski** [comment]
Hi, yes this is the behaviour I assumed but it does not work that way on my device. It seems to always open the tab no matter the scrolling distance. 

I will wait if others report the same issue as well, there's a good chance it is specific to my model/generation. I will be getting a new phone (Google Pixel) in a couple of weeks anyways and update you if it persists.

**Comment by oxdc** [comment]
Thank you @shef-ski ! This is more likely to be platform specific, rather than model specific. Android and iOS use different web engines, the exact behavior of touch events might be a little bit different. Most likely some events are not correctly fired. If possible, could you please try to use USB cable to connect your Android phone to a computer with Chrome installed? I'm not familiar with Android dev. If I'm correct, you can enable remote debug in Chrome to test if the events are fired as expected. (Don't worry if you are inconvenient. These are optional. Maybe someone can help me out.)

**Comment by oxdc** [comment]
Hi @shef-ski ! I got access to a Pixel device with the latest Android system installed. I cannot reproduce this bug in a newly created vault with the latest version of Obsidian. Please make sure to regularly update Obsidian and Vertical Tabs, and sticking to the official web engine. (Some vendors have bad reputation for forcing users to use their customized legacy engines.) Thank you.

**Comment by oxdc** [comment]
Hi @shef-ski ! A few weeks later, I may have access to several additional devices with custom and outdated engines. I'll try to reproduce the issue. If you have any idea or update, please feel free to comment below. Thank you.

**Comment by shef-ski** [comment]
Hi, just wanted to let you know that I now have a new device (Pixel 9) where I cloned the exact same vault and the issue disappeared. Probably something related to my previous phone / model.
