### ISSUE TITLE
Pinned tabs duplicate

### ISSUE THREAD

**Issue by kmaustral** [oxdc/obsidian-vertical-tabs#74]
When opening tabs, none of the Navigation Strategies seem to avoid duplication if the initial tab is pinned. IDE and Notebook avoid duplication only if the tab is unpinned. Can this be changed?

**Comment by oxdc** [comment]
Hi @kmaustral ! This is unexpected. Could you please provide the steps to reproduce? Thank you!

**Comment by kmaustral** [comment]
Sure.

   1. Note in sidebar with link to note in window which is pinned.
   2. Click link and note opens a second time alongside the pinned version

**Comment by oxdc** [comment]
Hi @kmaustral ! If I'm correct, in your case, a pinned note is in the sidebar. If you try to open this note again, another tab of it will open in the main area. This is the designed default behavior for now. Tab deduplication only works in the main area by default because most users treat the sidebar as a special area. I'll add an option to deduplicate sidebar tabs. Thank you!

**Comment by kmaustral** [comment]
Note quote. I click a link from a note in the sidebar to a different note
in the pane which is already pinned. It then opens a duplicate. It doesn't
do this if the note is unpinned.

**Comment by oxdc** [comment]
Hi @kmaustral ! Unfortunately, I cannot reproduce based on your description. I'm not sure if I understand correctly. Could you please try to reproduce in a [Sandbox vault](https://help.obsidian.md/Getting+started/Sandbox+vault)? If the problem still exists in the Sandbox, could you please record a video with all the steps required to reproduce the bug, and upload it here? Thank you so much!

**Comment by oxdc** [comment]
Hi @kmaustral ! Since I cannot reproduce this issue in the latest version, I am closing it for now. The next version will include some improvements, so when it is released, please upgrade and test again. If you still encounter the issue after the update, feel free to reopen it. Thank you for your understanding.

**Comment by kmaustral** [comment]
Thanks. Sorry I haven't had time to sandbox the issue. But one other
problem has come up with Plugin Update Tracker. With Vertical Tabs
installed, the plugin update screen cannot stay focused. It continually
reverts to the next open tab.

**Comment by oxdc** [comment]
Hi @kmaustral ! Thank you.

> But one other problem has come up with Plugin Update Tracker. With Vertical Tabs installed, the plugin update screen cannot stay focused. It continually reverts to the next open tab.

I have fixed this issue.
